server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          #username:  xwbGithub
          #password: xxx
          uri: https://github.com/kurl88/spring-cloud-config-test.git #github上的原始地址