server:
  port: 8091
eureka:
  client:
    register-with-eureka: false #自己是否可以注册
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/